name: esp_rainmaker
description: A wrapper of the ESP Rainmaker REST API for client-cloud communication.
version: 0.3.0
homepage: https://github.com/chmoore889/esp_rainmaker.git

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  http: ^0.12.2
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
