name: esp_rainmaker
description: A wrapper of the ESP Rainmaker REST API for client-cloud communication.
version: 1.0.0-nullsafety.0
homepage: https://github.com/chmoore889/esp_rainmaker

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  http: ^0.13.0-nullsafety.0
  meta: ^1.2.4

  isolate_json: ^2.0.0-nullsafety.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
