name: esp_rainmaker
description: A wrapper of the ESP Rainmaker REST API for client-cloud communication.
version: 1.0.0
homepage: https://github.com/chmoore889/esp_rainmaker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

  isolate_json: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.1
